version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
configuration: Release

# Scripts
for:
-
    matrix:
        only:
            - image: Visual Studio 2019
    install:
    - ps: >-
        Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1';
        
        .\dotnet-install.ps1 -Channel master;
    before_build:
    - ps: >-
        nuget restore;
        
        dotnet restore;
-
    matrix:
        only:
            - image: Ubuntu
    install:
    - sh: >-
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel master
    before_build:
    - sh: >-
        dotnet restore

# Build settings
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal

# Deploy
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ggg-killer/api/v2/package
  api_key:
    secure: Ufjp6cc+x5kIt10jHw5MIw+S9ywdZtFDUEQ6NiQe01bnkH6p2p241NXg8GViF1XQ
  skip_symbols: false
  symbol_server: https://www.myget.org/F/ggg-killer/symbols/api/v2/package
  on:
    branch: master

# Notifications
notifications:
- provider: Email
  to:
  - gggkiller2@gmail.com
  subject: AppVeyor - GUtils.NET - Build Failure
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
